{
 "title": "Time to Observed",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "network",
    "query": {
     "query": "label_values(beacon_head_slot,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gossip Delay Distribution ($network, 1h)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_gossip{job = \"$network\"}[1h]\n",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Gossip Delay Distribution ($network, 24h)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_gossip{job = \"$network\"}[24h]\n",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Head Hit Probability ($network)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*increase(validator_monitor_attestation_simulator_head_attester_hit_total{job=\"$network\"}[768s]) /\n (increase(validator_monitor_attestation_simulator_head_attester_hit_total{job=\"$network\"}[768s]) +\n increase(validator_monitor_attestation_simulator_head_attester_miss_total{job=\"$network\"}[768s]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Slot Data Arrival ($network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.05,beacon_block_delay_observed_slot_start{job=\"$network\"}[1152s])",
     "legendFormat": "Q[0.05]"
    },
    {
     "expr": "quantile_over_time(0.32,beacon_block_delay_observed_slot_start{job=\"$network\"}[1152s])",
     "legendFormat": "Q[0.32]"
    },
    {
     "expr": "quantile_over_time(0.5,beacon_block_delay_observed_slot_start{job=\"$network\"}[1152s])",
     "legendFormat": "Q[0.5]"
    },
    {
     "expr": "quantile_over_time(0.68,beacon_block_delay_observed_slot_start{job=\"$network\"}[1152s])",
     "legendFormat": "Q[0.68]"
    },
    {
     "expr": "quantile_over_time(0.95,beacon_block_delay_observed_slot_start{job=\"$network\"}[1152s])",
     "legendFormat": "Q[0.95]"
    },
    {
     "expr": "quantile_over_time(0.99,beacon_block_delay_observed_slot_start{job=\"$network\"}[1152s])",
     "legendFormat": "Q[0.99]"
    },
    {
     "expr": "avg_over_time(beacon_block_delay_gossip{job=\"$network\"}[12s])",
     "legendFormat": "gossip slot"
    },
    {
     "expr": "avg_over_time(beacon_block_delay_gossip{job=\"$network\"}[384s])",
     "legendFormat": "gossip epoch"
    }
   ]
  },
  {
   "title": "Gossip Peer Count ($network)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "gossipsub_topic_peers_5m_min{job=~\"$network\"}",
     "legendFormat": "min"
    },
    {
     "expr": "gossipsub_topic_peers_5m_mean{job=~\"$network\"}",
     "legendFormat": "mean"
    },
    {
     "expr": "gossipsub_topic_peers_5m_mean{job=~\"$network\"} - gossipsub_topic_peers_5m_stddev{job=~\"$network\"}",
     "legendFormat": "-sigma"
    },
    {
     "expr": "gossipsub_topic_peers_5m_mean{job=~\"$network\"} + gossipsub_topic_peers_5m_stddev{job=~\"$network\"}",
     "legendFormat": "+sigma"
    },
    {
     "expr": "gossipsub_topic_peers_5m_max{job=~\"$network\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Peer Count Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "gossipsub_topic_peers_5m_avg{job=~\"$network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Count Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "gossipsub_topic_peers_5m_avg{job=~\"$network\"}",
     "legendFormat": "Peers Detected"
    }
   ]
  }
 ]
}