{
 "title": "Validator Performance",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "network",
    "query": {
     "query": "label_values(beacon_head_state_root,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "New Payload Duration ($network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "  rpc_duration_engine_newPayloadV4_success{job=\"$network\",quantile=~\"0.95\"}",
     "legendFormat": "Q[{{quantile}}]"
    },
    {
     "expr": "quantile_over_time(0.95,\n  rpc_duration_engine_newPayloadV4_success{job=\"$network\",quantile=~\"0.95\"}[384s]\n)",
     "legendFormat": "Avg-{{quantile}}"
    },
    {
     "expr": "quantile_over_time(0.95,\n  rpc_duration_engine_newPayloadV4_success{job=\"$network\",quantile=~\"0.95\" }[32m]\n)",
     "legendFormat": "Avg32-{{quantile}}"
    }
   ]
  },
  {
   "title": "Fork Choice Updated ($network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rpc_duration_engine_forkchoiceUpdatedV3_success{quantile=~\"0.95\",job=~\"$network\"}    ",
     "legendFormat": "Q[{{quantile}}]"
    },
    {
     "expr": "avg_over_time(\n  rpc_duration_engine_forkchoiceUpdatedV3_success{quantile=~\"0.95\", job=\"$network\"}[5m]\n)",
     "legendFormat": "Avg-{{quantile}}"
    },
    {
     "expr": "avg_over_time(\n  rpc_duration_engine_forkchoiceUpdatedV3_success{quantile=~\"0.95\", job=\"$network\"}[32m]\n)",
     "legendFormat": "Ave32-{{quantile}}"
    }
   ]
  },
  {
   "title": "Attestable Breakdown ($network)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(beacon_block_delay_consensus_verification_time{job=\"$network\"}[1m])",
     "legendFormat": "verify"
    },
    {
     "expr": "avg_over_time(\n  beacon_block_delay_execution_time{job=\"$network\"}[36s]\n)",
     "legendFormat": "execute"
    },
    {
     "expr": "avg_over_time(beacon_block_delay_observed_slot_start{job=\"$network\"}[36s])",
     "legendFormat": "observed"
    },
    {
     "expr": "avg_over_time(beacon_block_delay_attestable_slot_start{job=\"$network\"}[36s])",
     "legendFormat": "attestable"
    },
    {
     "expr": "quantile_over_time(0.95,beacon_block_delay_attestable_slot_start{job=\"$network\"}[36s])",
     "legendFormat": "attestable-0.95"
    },
    {
     "expr": "min_over_time(beacon_block_delay_attestable_slot_start{job=\"$network\"}[36s])",
     "legendFormat": "attestable-min"
    },
    {
     "expr": "beacon_block_delay_observed_slot_start{job=\"$network\"}",
     "legendFormat": "observed-instant"
    }
   ]
  },
  {
   "title": "Head Hit Probability ($network)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*increase(validator_monitor_attestation_simulator_head_attester_hit_total{job=\"$network\"}[384s]) /\n (increase(validator_monitor_attestation_simulator_head_attester_hit_total{job=\"$network\"}[384s]) +\n increase(validator_monitor_attestation_simulator_head_attester_miss_total{job=\"$network\"}[384s]))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}